server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shenjia
    password: 123456
    url: jdbc:mysql://localhost:3306/finance_product?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&useSSL=false
  application:
    name: sparkle-product