spring:
  application:
    name: sparkle-consumer
  profiles:
    active: dev
logging:
  level:
    com.sparkle: trace
server:
  undertow:
    buffer-size: 1024
    direct-buffers: on
    always-set-keep-alive: true